// Mock library data for MusicKit prototype.
// Single-source. ARTISTS contains everything; albums and tracks denormalized below.

const ARTISTS = [
  {
    id: "a-enya",
    name: "Enya",
    sortName: "Enya",
    albumCount: 3,
    trackCount: 40,
    bio: "Irish singer, songwriter and musician. Known for layered vocals, Celtic textures, and dreamlike production.",
    color: "#9d1c1f",
    albums: [
      {
        id: "al-tvbe",
        name: "The Very Best Of Enya",
        year: 2009,
        trackCount: 18,
        color: "#9d1c1f",
        cover: "enya",
        tracks: [
          { n: 1, title: "Orinoco Flow", time: "04:28" },
          { n: 2, title: "Aniron (I Desire)", time: "02:43", starred: true },
          { n: 3, title: "Storms In Africa", time: "04:04" },
          { n: 4, title: "Caribbean Blue", time: "03:59" },
          { n: 5, title: "Book Of Days", time: "02:55" },
          { n: 6, title: "The Celts", time: "02:57" },
          { n: 7, title: "Only Time", time: "03:38" },
          { n: 8, title: "Wild Child", time: "03:47" },
          { n: 9, title: "Water Shows The Hidden Heart", time: "04:39" },
          { n: 10, title: "Anywhere Is", time: "03:59" },
          { n: 11, title: "Cursum Perficio", time: "04:09" },
          { n: 12, title: "Amarantine", time: "03:12" },
          { n: 13, title: "Aldebaran", time: "03:06" },
          { n: 14, title: "Trains And Winter Rains", time: "03:43" },
          { n: 15, title: "Watermark", time: "02:25" },
          { n: 16, title: "Boadicea", time: "03:32", starred: true },
          { n: 17, title: "A Day Without Rain", time: "02:37", starred: true },
          { n: 18, title: "May It Be", time: "03:31", starred: true },
        ],
      },
      {
        id: "al-watermark",
        name: "Watermark",
        year: 1988,
        trackCount: 11,
        color: "#5a7a8a",
        cover: "watermark",
        tracks: [
          { n: 1, title: "Watermark", time: "02:25" },
          { n: 2, title: "Cursum Perficio", time: "04:09" },
          { n: 3, title: "On Your Shore", time: "04:00" },
          { n: 4, title: "Storms In Africa", time: "04:04" },
          { n: 5, title: "Exile", time: "04:20" },
          { n: 6, title: "Miss Clare Remembers", time: "01:59" },
          { n: 7, title: "Orinoco Flow", time: "04:28" },
          { n: 8, title: "Evening Falls...", time: "03:46" },
          { n: 9, title: "River", time: "03:11" },
          { n: 10, title: "The Longships", time: "03:36" },
          { n: 11, title: "Na Laetha Geal M'óige", time: "03:55" },
        ],
      },
      {
        id: "al-shepmoon",
        name: "Shepherd Moons",
        year: 1991,
        trackCount: 12,
        color: "#3a3552",
        cover: "shep",
        tracks: [
          { n: 1, title: "Shepherd Moons", time: "03:38" },
          { n: 2, title: "Caribbean Blue", time: "03:59" },
          { n: 3, title: "How Can I Keep From Singing?", time: "04:23" },
          { n: 4, title: "Ebudæ", time: "01:53" },
          { n: 5, title: "Angeles", time: "04:01" },
          { n: 6, title: "No Holly For Miss Quinn", time: "02:39" },
          { n: 7, title: "Book Of Days", time: "02:55" },
          { n: 8, title: "Marble Halls", time: "03:53" },
          { n: 9, title: "Afer Ventus", time: "04:04" },
          { n: 10, title: "Smaointe...", time: "06:08" },
        ],
      },
    ],
  },
  {
    id: "a-beach-house",
    name: "Beach House",
    sortName: "Beach House",
    albumCount: 2,
    trackCount: 19,
    bio: "Baltimore dream-pop duo. Slow-burn synths, reverberant guitars, Victoria Legrand's contralto.",
    color: "#d8a5b8",
    albums: [
      {
        id: "al-depression",
        name: "Depression Cherry",
        year: 2015,
        trackCount: 9,
        color: "#a83246",
        cover: "depression",
        tracks: [
          { n: 1, title: "Levitation", time: "05:09" },
          { n: 2, title: "Sparks", time: "05:21", starred: true },
          { n: 3, title: "Space Song", time: "05:21", starred: true },
          { n: 4, title: "Beyond Love", time: "04:25" },
          { n: 5, title: "10:37", time: "04:30" },
          { n: 6, title: "PPP", time: "06:01" },
          { n: 7, title: "Wildflower", time: "04:30" },
          { n: 8, title: "Bluebird", time: "05:21" },
          { n: 9, title: "Days Of Candy", time: "06:15" },
        ],
      },
      {
        id: "al-teendream",
        name: "Teen Dream",
        year: 2010,
        trackCount: 10,
        color: "#1d4d5c",
        cover: "teendream",
        tracks: [
          { n: 1, title: "Zebra", time: "04:51" },
          { n: 2, title: "Silver Soul", time: "04:59" },
          { n: 3, title: "Norway", time: "04:00" },
          { n: 4, title: "Walk In The Park", time: "05:18" },
          { n: 5, title: "Used To Be", time: "03:53" },
          { n: 6, title: "Lover Of Mine", time: "04:55" },
          { n: 7, title: "Better Times", time: "04:18" },
          { n: 8, title: "10 Mile Stereo", time: "05:01" },
          { n: 9, title: "Real Love", time: "05:00" },
          { n: 10, title: "Take Care", time: "05:55" },
        ],
      },
    ],
  },
  {
    id: "a-aphex",
    name: "Aphex Twin",
    sortName: "Aphex Twin",
    albumCount: 2,
    trackCount: 20,
    bio: "Richard D. James — pioneer of IDM and ambient electronics. Cornish weirdo, sui generis.",
    color: "#3d8a4a",
    albums: [
      {
        id: "al-saw2",
        name: "Selected Ambient Works Vol. II",
        year: 1994,
        trackCount: 10,
        color: "#222932",
        cover: "saw2",
        tracks: [
          { n: 1, title: "#1", time: "04:34" },
          { n: 2, title: "Cliffs", time: "08:09" },
          { n: 3, title: "Radiator", time: "04:34" },
          { n: 4, title: "Rhubarb", time: "07:43", starred: true },
          { n: 5, title: "Hankie", time: "04:23" },
          { n: 6, title: "Grass", time: "06:14" },
          { n: 7, title: "Mould", time: "05:00" },
          { n: 8, title: "Curtains", time: "06:19" },
          { n: 9, title: "Lichen", time: "04:33" },
          { n: 10, title: "Spots", time: "07:00" },
        ],
      },
      {
        id: "al-syro",
        name: "Syro",
        year: 2014,
        trackCount: 10,
        color: "#b86b1a",
        cover: "syro",
        tracks: [
          { n: 1, title: "minipops 67 [120.2][source field mix]", time: "04:47" },
          { n: 2, title: "XMAS_EVET10 [120][thanaton3 mix]", time: "10:30" },
          { n: 3, title: "produk 29 [101]", time: "05:46" },
          { n: 4, title: "4 bit 9d api+e+6 [126.26]", time: "07:18" },
          { n: 5, title: "180db_ [130]", time: "00:48" },
          { n: 6, title: "CIRCLONT6A [141.98][syrobonkus mix]", time: "06:39" },
          { n: 7, title: "fz pseudotimestretch+e+3 [138.85]", time: "01:00" },
          { n: 8, title: "CIRCLONT14 [152.97][shrymoming mix]", time: "07:25" },
          { n: 9, title: "syro u473t8+e [141.98][piezoluminescence mix]", time: "06:11" },
          { n: 10, title: "PAPAT4 [155][pineal mix]", time: "06:11" },
        ],
      },
    ],
  },
  {
    id: "a-sigur",
    name: "Sigur Rós",
    sortName: "Sigur Ros",
    albumCount: 1,
    trackCount: 8,
    bio: "Icelandic post-rock; bowed guitar, glaciers, falsetto.",
    color: "#7ba6c9",
    albums: [
      {
        id: "al-takk",
        name: "Takk...",
        year: 2005,
        trackCount: 8,
        color: "#a9c4d8",
        cover: "takk",
        tracks: [
          { n: 1, title: "Takk...", time: "01:57" },
          { n: 2, title: "Glósóli", time: "06:15" },
          { n: 3, title: "Hoppípolla", time: "04:28", starred: true },
          { n: 4, title: "Með Blóðnasir", time: "02:17" },
          { n: 5, title: "Sé Lest", time: "08:40" },
          { n: 6, title: "Sæglópur", time: "07:38" },
          { n: 7, title: "Mílanó", time: "10:25" },
          { n: 8, title: "Gong", time: "06:24" },
        ],
      },
    ],
  },
  {
    id: "a-eno",
    name: "Brian Eno",
    sortName: "Eno, Brian",
    albumCount: 1,
    trackCount: 6,
    bio: "Producer, ambient pioneer, inventor of the term.",
    color: "#c9b87a",
    albums: [
      {
        id: "al-airports",
        name: "Ambient 1: Music For Airports",
        year: 1978,
        trackCount: 4,
        color: "#8a9c7a",
        cover: "airports",
        tracks: [
          { n: 1, title: "1/1", time: "17:21" },
          { n: 2, title: "2/1", time: "08:21" },
          { n: 3, title: "1/2", time: "11:30" },
          { n: 4, title: "2/2", time: "09:39" },
        ],
      },
    ],
  },
  {
    id: "a-boc",
    name: "Boards of Canada",
    sortName: "Boards of Canada",
    albumCount: 1,
    trackCount: 17,
    bio: "Scottish duo, hauntological electronica, faded VHS-warm pads.",
    color: "#a87a3d",
    albums: [
       {
        id: "al-mhtrtc",
        name: "Music Has The Right To Children",
        year: 1998,
        trackCount: 17,
        color: "#c98a4a",
        cover: "mhtrtc",
        tracks: [
          { n: 1, title: "Wildlife Analysis", time: "01:18" },
          { n: 2, title: "An Eagle In Your Mind", time: "06:23" },
          { n: 3, title: "The Color Of The Fire", time: "01:45" },
          { n: 4, title: "Telephasic Workshop", time: "06:35" },
          { n: 5, title: "Triangles & Rhombuses", time: "01:50" },
          { n: 6, title: "Sixtyten", time: "05:48" },
          { n: 7, title: "Turquoise Hexagon Sun", time: "05:08" },
          { n: 8, title: "Kaini Industries", time: "00:59" },
          { n: 9, title: "Bocuma", time: "01:35" },
          { n: 10, title: "Roygbiv", time: "02:30", starred: true },
          { n: 11, title: "Rue The Whirl", time: "06:39" },
          { n: 12, title: "Aquarius", time: "05:58" },
          { n: 13, title: "Olson", time: "01:31" },
          { n: 14, title: "Pete Standing Alone", time: "06:07" },
          { n: 15, title: "Smokes Quantity", time: "03:08" },
          { n: 16, title: "Open The Light", time: "04:26" },
          { n: 17, title: "One Very Important Thought", time: "01:13" },
        ],
      },
    ],
  },
];

const STATIONS = [
  { id: "s1", name: "NRK mP3", url: "https://radio.nrk.no/direkte/mp3", country: "NO" },
  { id: "s2", name: "NRK P3", url: "https://radio.nrk.no/direkte/p3", country: "NO" },
  { id: "s3", name: "NRK P3 Musikk", url: "https://radio.nrk.no/direkte/p3musikk", country: "NO" },
  { id: "s4", name: "NRK Nyheter", url: "https://radio.nrk.no/direkte/nyheter", country: "NO" },
  { id: "s5", name: "SomaFM — Groove Salad", url: "https://somafm.com/groovesalad", country: "US" },
  { id: "s6", name: "SomaFM — Drone Zone", url: "https://somafm.com/dronezone", country: "US" },
  { id: "s7", name: "BBC Radio 6 Music", url: "https://bbc.co.uk/6music", country: "UK" },
  { id: "s8", name: "FIP", url: "https://fip.fr", country: "FR" },
];

// Lyric snippet for the lyrics overlay demo.
const LYRICS_BOADICEA = [
  "[instrumental — wordless vocal piece]",
  "",
  "ah… ah-ah… ah…",
  "(soaring layered vowels)",
  "ah… ah-ah… ah…",
  "",
  "ooh… ooh-oo-ooh…",
  "(harmonies stack into a wash)",
  "ah… ah-ah… ah…",
  "",
  "— Composed and performed by Enya, 1987",
  "— No lyrics; this is sung in pure vowel sounds",
];

window.MK_DATA = { ARTISTS, STATIONS, LYRICS_BOADICEA };
